### PR TITLE
Change exe name to `crc-background-launcher.exe`

### PR DESCRIPTION
**Pull request by anjannath**

### CODE REVIEW

**Review by cfergeau — CHANGES_REQUESTED** [review]
An explanation why we want to make this change is missing from the commit log.

**Comment by anjannath** [comment]
> An explanation why we want to make this change is missing from the commit log.

have updated the commit message now, thanks!

**Review by gbraad — APPROVED** [review]

**Comment by gbraad** [comment]
This resolves the issue of not being an easily identifiable binary; if a quarantine popup or process list shows this process, the user is able to determine this belongs to `crc`.

**Comment by cfergeau** [comment]
> This resolves the issue of not being an easily identifiable binary; if a quarantine popup or process list shows this process, the user is able to determine this belongs to `crc`

This is not going to scale if other projects want to make use of this binary (gvisor-tap-vsock, podman, ..). And this will make it look like it's crc-specific to potential users, when it's not.

**Comment by gbraad** [comment]
Projects can be re-used, but installer installed binaries shouldn't as they are specific to what we deliver as a tested experience. This means we will name them `crc-` for our usecase. It is crc-specific from our installer.

`podman` is a bad example, as we do not depend on it from CRC. We depend on it from the bundle we install, and we merely expose the command to the user.

`gvisor-tap-vsock` is currently integrated as part of our daemon. if we can use a globally installed binary, it would not exist in the crc folder, right?

Note: the follow-up can be to name the binary from the installer, but let's first confirm this works as expected.

**Comment by cfergeau** [comment]
> This means we will name them crc- for our usecase. It is crc-specific from our installer.

Then this should be renamed during crc build, or as part of install, ...

> podman is a bad example, as we do not depend on it from CRC. We depend on it from the bundle we install, and we merely expose the command to the user.

Then it's a good example. As you said, podman and CRC are independant code bases. If podman-machine wants to use the `win32-background-launcher` instead of the code they have to start gvproxy, it makes no sense for them if the binary is named `crc-background-launcher`.

**Pull request merged**
